stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:27.2.0-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - |
      docker build \
        --build-arg NEXT_PUBLIC_FASTAPI_BASE_URL="$NEXT_PUBLIC_FASTAPI_BASE_URL" \
        --build-arg NEXT_PUBLIC_CDN_URL="$NEXT_PUBLIC_CDN_URL" \
        -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" \
        -f Dockerfile.prod .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  variables:
    AWS_DEFAULT_REGION: ap-south-1
    ROLE_ARN: arn:aws:iam::955719296501:role/ec2-ssm-gitlab
  before_script:
    - curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
    - dpkg -i session-manager-plugin.deb
    - mkdir -p ~/.aws
    - echo "${GITLAB_OIDC_TOKEN}" > /tmp/web_identity_token
    - echo -e "[profile default]\nrole_arn=${ROLE_ARN}\nweb_identity_token_file=/tmp/web_identity_token" > ~/.aws/config
  script:
    - aws sts get-caller-identity
    - chmod +x deploy-to-ec2.sh
    - ./deploy-to-ec2.sh